### ISSUE TITLE
Bot hang on "switching to"

### ISSUE THREAD

**Issue by Kraker01** [KeinNameVorhanden/poggat#1]
Idler is installed correctly (latest Node, latest Chrome), everything is set up, but sometimes it hangs up on "Switching to" without moving on (setting low resolution, setting a starting and finishing time...)

Is there any debug I could do to fix the problem?

**Comment by KeinNameVorhanden** [comment]
Whats your twitch language?

For 'debug' change headless from true to false and observe.

**Comment by Kraker01** [comment]
Language was set to "Italian", changed it to English, it worked.

Il giorno mer 18 ago 2021 alle ore 17:07 www ***@***.***> ha
scritto:

**Comment by KeinNameVorhanden** [comment]
Added 'support' for some other languages in [0.3.4.6](https://github.com/KeinNameVorhanden/poggat/commit)
